import { Professional, Booking } from '../types';

export const mockProfessionals: Professional[] = [
  {
    id: 'p1',
    name: 'Rajesh Kumar Singh',
    nameHi: 'राजेश कुमार सिंह',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.9,
    reviewCount: 148,
    experience: 16,
    district: 'Bhagalpur',
    districtHi: 'भागलपुर',
    block: 'Jagdishpur',
    office: 'Bhagalpur Sadar Registry Office',
    officeHi: 'भागलपुर सदर रजिस्ट्री ऑफिस',
    officeType: 'Registry Office',
    chamberAddress: 'Shed No. 14, Near Sub-Registrar Gate, Registry Office Campus, Bhagalpur',
    verified: true,
    licenseNumber: 'BGP/DW/2009/482',
    licenseAuthority: 'District Registration Department, Bihar',
    fee: 2000,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed (Hibanama)', 'Partition Deed (Batwarinama)', 'Agreement to Sale'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'दान पत्र (हिबानामा)', 'बंटवारानामा', 'बिक्री इकरारनामा'],
    languages: ['Hindi', 'Angika', 'English'],
    image: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=300&auto=format&fit=crop&q=80',
    about: 'Senior Licensed Deed Writer (Katib) with 16+ years of expertise in Bhagalpur district. Expert in drafting error-free Kewala deeds, boundary verification (Chauhaddi), and immediate registry token clearance.',
    aboutHi: 'भागलपुर जिले में 16+ वर्षों के अनुभव के साथ वरिष्ठ लाइसेंस प्राप्त कातिब। त्रुटिरहित केवाला लेखन, चौहद्दी मिलान और त्वरित निबंधन में विशेषज्ञता।',
    phone: '+91 94312 88410',
    whatsapp: '+91 94312 88410',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
    totalCasesCompleted: 1420,
    reviews: [
      {
        id: 'r1',
        userName: 'Manoj Choudhary',
        userLocation: 'Sabour, Bhagalpur',
        rating: 5,
        date: '12 Aug 2026',
        comment: 'Rajesh ji drafted our commercial land kewala in just 3 hours. Handled the circle rate calculation and token without any hassle. Highly recommended!',
        verifiedBooking: true
      },
      {
        id: 'r2',
        userName: 'Sunita Devi',
        userLocation: 'Nathnagar',
        rating: 5,
        date: '28 Jul 2026',
        comment: 'Very honest Katib. Transparent regarding official stamp duty. No hidden charges.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p2',
    name: 'Advocate Anand Vardhan',
    nameHi: 'अधिवक्ता आनंद वर्धन',
    category: 'Lawyer',
    categoryHi: 'जमीन एवं संपत्ति वकील',
    rating: 4.9,
    reviewCount: 96,
    experience: 14,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Patna Sadar',
    office: 'Patna High Court',
    officeHi: 'पटना उच्च न्यायालय एवं सिविल कोर्ट',
    officeType: 'Civil Court',
    chamberAddress: 'Chamber #204, High Court Advocates Association / Danapur Registry Road, Patna',
    verified: true,
    licenseNumber: 'BR/PAT/2012/8821',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 3500,
    tokenFee: 100,
    services: ['30-Year Title Search', 'Dakhil Kharij Dispute', 'DCLR / BLT Appeals', 'Land Partition Suit', 'Legal Opinion Certificate'],
    servicesHi: ['30 वर्षीय टाइटल जांच', 'दाखिल-खारिज विवाद', 'डीसीएलआर अपील', 'जमीन बंटवारा वाद', 'कानूनी राय प्रमाण पत्र'],
    languages: ['Hindi', 'Bhojpuri', 'English', 'Magahi'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    about: 'Practicing Land & Property Lawyer representing clients in Patna High Court, Civil Courts, and District Revenue Forums. Specializes in ancestral title checks and complex Dakhil Kharij rejections.',
    aboutHi: 'पटना हाईकोर्ट और राजस्व न्यायालयों में सक्रिय संपत्ति अधिवक्ता। पुश्तैनी जमीन के स्वामित्व प्रमाणन व विवादित दाखिल-खारिज मामलों में विशेषज्ञ।',
    phone: '+91 98350 44129',
    whatsapp: '+91 98350 44129',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '12:00 PM', '02:30 PM', '04:30 PM', '06:00 PM'],
    totalCasesCompleted: 890,
    reviews: [
      {
        id: 'r3',
        userName: 'Alok Ranjan',
        userLocation: 'Kankarbagh, Patna',
        rating: 5,
        date: '05 Aug 2026',
        comment: 'Advocate Anand did a complete 30-year search report on our plot in Bihta. Saved us from a disputed property with multiple fake claimants.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p3',
    name: 'Amin Ramashish Yadav',
    nameHi: 'अमीन रामाशीष यादव',
    category: 'Amin / Land Surveyor',
    categoryHi: 'सरकारी प्रशिक्षित अमीन (भूमि सर्वेयर)',
    rating: 4.8,
    reviewCount: 112,
    experience: 19,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Danapur',
    office: 'Danapur Sub-Registry',
    officeHi: 'दानापुर अवर-निबंधन व अंचल कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Near Danapur Block Circle Office, Khagaul Road, Danapur',
    verified: true,
    licenseNumber: 'BHR/AMIN/PAT/9871',
    licenseAuthority: 'Revenue & Land Reforms Dept, Bihar',
    fee: 2200,
    tokenFee: 100,
    services: ['Land Measurement (Katha/Dhur)', 'ETS Electronic Survey', 'Boundary Demarcation (Hadbandi)', 'Revisional Map Naksha Matching'],
    servicesHi: ['कट्ठा/धूर/डिसमिल जमीन नापी', 'ईटीएस इलेक्ट्रॉनिक पैमाइश', 'हदबंदी एवं सीमा पिलर', 'राजस्व नक्शा मिलान'],
    languages: ['Hindi', 'Bhojpuri', 'Magahi'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    about: 'Govt Certified Senior Amin with Gunter Chain, Total Station & GPS mapping expertise. Has surveyed over 4,000 plots in Patna, Danapur, Bihta, and Naubatpur blocks without boundary inaccuracies.',
    aboutHi: 'सरकारी प्रमाणित वरिष्ठ अमीन। जरीब (चेन), टोटल स्टेशन एवं जीपीएस द्वारा सटीक पैमाइश। दानापुर, बिहटा और पटना अंचल में 4000+ खेतों और प्लॉटों का सफल सीमांकन।',
    phone: '+91 94702 11984',
    whatsapp: '+91 94702 11984',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday'],
    timeSlots: ['07:30 AM', '09:00 AM', '11:00 AM', '03:00 PM'],
    totalCasesCompleted: 2150,
    reviews: [
      {
        id: 'r4',
        userName: 'Surendra Prasad',
        userLocation: 'Naubatpur, Patna',
        rating: 5,
        date: '02 Aug 2026',
        comment: 'Ramashish ji resolved a 5-year old boundary confusion with the neighbor in 2 hours using village cadastral map.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p4',
    name: 'Santosh Kumar Mishra (Notary)',
    nameHi: 'संतोष कुमार मिश्रा (नोटरी)',
    category: 'Notary',
    categoryHi: 'नोटरी पब्लिक (भारत सरकार)',
    rating: 4.9,
    reviewCount: 73,
    experience: 11,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur Registry Office Notary Complex',
    officeHi: 'मुजफ्फरपुर निबंधन कार्यालय नोटरी परिसर',
    officeType: 'Registry Office',
    chamberAddress: 'Collectorate Campus, Opposite Sub-Registry Building, Muzaffarpur',
    verified: true,
    licenseNumber: 'GOI/NOT/MZP/4419',
    licenseAuthority: 'Ministry of Law & Justice, Govt of India',
    fee: 800,
    tokenFee: 100,
    services: ['Agreement Attestation', 'Land Affidavit / Shapath Patra', 'General Power of Attorney (GPA)', 'Will Notarization'],
    servicesHi: ['एग्रीमेंट सत्यापन', 'जमीन शपथ पत्र', 'मुख्तारनामा (GPA)', 'वसीयतनामा प्रमाणीकरण'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    about: 'Government Appointed Notary Public for Muzaffarpur district. Instant stamping, online register entry, and tamper-proof security holographic attestations.',
    aboutHi: 'मुजफ्फरपुर जिले के लिए भारत सरकार द्वारा नियुक्त नोटरी पब्लिक। तुरंत शपथ पत्र प्रमाणीकरण व सुरक्षित होलोग्राम सत्यापन।',
    phone: '+91 93081 77209',
    whatsapp: '+91 93081 77209',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '01:30 PM', '03:30 PM', '05:00 PM'],
    totalCasesCompleted: 3100,
    reviews: [
      {
        id: 'r5',
        userName: 'Vikash Jha',
        userLocation: 'Kanti, Muzaffarpur',
        rating: 5,
        date: '10 Aug 2026',
        comment: 'Quick and hassle-free affidavit for our land mutation submission at Circle Office.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p5',
    name: 'Birendra Kumar Jha',
    nameHi: 'बीरेन्द्र कुमार झा',
    category: 'Deed Writer',
    categoryHi: 'वरिष्ठ दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 88,
    experience: 22,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur Registry Office',
    officeHi: 'मुजफ्फरपुर रजिस्ट्री कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Shed No. 7, Main Registry Campus, Club Road, Muzaffarpur',
    verified: true,
    licenseNumber: 'MZP/KATIB/2004/219',
    licenseAuthority: 'District Registration Office, Muzaffarpur',
    fee: 1800,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Exchange Deed (Badlainama)', 'Gift Deed (Hibanama)', 'Lease Registration'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'बदलैननामा (जमीन अदला-बदली)', 'हिबानामा', 'लीज पट्टा रजिस्ट्री'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    about: '22+ years seasoned Katib in Muzaffarpur district. Expert in drafting Kewala deeds for urban residential plots, MVR calculation, and token filing at Muzaffarpur Registry Office.',
    aboutHi: 'मुजफ्फरपुर जिले में 22+ वर्षों के अनुभवी कातिब। आवासीय एवं व्यावसायिक प्लॉटों का केवाला लेखन और त्वरित टोकन निबंधन।',
    phone: '+91 94318 66201',
    whatsapp: '+91 94318 66201',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 2840,
    reviews: [
      {
        id: 'r6',
        userName: 'Abhishek Mishra',
        userLocation: 'Kanti, Muzaffarpur',
        rating: 5,
        date: '04 Aug 2026',
        comment: 'Very thorough with Khatiyan entries and legal clauses. No clerical error on the final stamp.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p6',
    name: 'Amin Kameshwar Sahni',
    nameHi: 'अमीन कामेश्वर सहनी',
    category: 'Amin / Land Surveyor',
    categoryHi: 'राजस्व अमीन (भूमि सर्वेयर)',
    rating: 4.9,
    reviewCount: 68,
    experience: 15,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Kanti',
    office: 'Kanti Sub-Registry',
    officeHi: 'कांटी अंचल व निबंधन कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Near Kanti Block Circle Office, Muzaffarpur',
    verified: true,
    licenseNumber: 'BHR/AMIN/MZP/5521',
    licenseAuthority: 'Revenue Department, Bihar',
    fee: 2000,
    tokenFee: 100,
    services: ['Land Measurement (Katha/Dhur)', 'Boundary Demarcation (Hadbandi)', 'Revisional Map Naksha Matching'],
    servicesHi: ['कट्ठा/धूर/डिसमिल जमीन नापी', 'हदबंदी एवं सीमा पिलर', 'राजस्व नक्शा मिलान'],
    languages: ['Hindi', 'Bajjika'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    about: 'Experienced revenue amin specializing in Kanti, Kurhani, and Musahari blocks of Muzaffarpur. Reliable physical plot measurement using Gunter chain and GPS coordinates.',
    aboutHi: 'कांटी और मुसहरी प्रखंड में विश्वसनीय अमीन पैमाइश। जरीब एवं जीपीएस द्वारा सटीक सीमांकन।',
    phone: '+91 97714 33290',
    whatsapp: '+91 97714 33290',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['08:00 AM', '10:30 AM', '02:00 PM', '04:00 PM'],
    totalCasesCompleted: 1100,
    reviews: [
      {
        id: 'r7',
        userName: 'Deepak Kumar',
        userLocation: 'Kanti, Muzaffarpur',
        rating: 5,
        date: '08 Aug 2026',
        comment: 'Accurate boundary marking and fast report. Very satisfied.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p7',
    name: 'Mohammad Tariq Anwar',
    nameHi: 'मोहम्मद तारिक अनवर',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 76,
    experience: 15,
    district: 'Gaya',
    districtHi: 'गया',
    block: 'Gaya Town',
    office: 'Gaya Sadar Registry Office',
    officeHi: 'गया सदर रजिस्ट्री कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Near Gaya Collectorate, Registry Campus, Gaya',
    verified: true,
    licenseNumber: 'GAY/DW/2011/391',
    licenseAuthority: 'Registration Department, Gaya',
    fee: 1900,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Hibanama (Gift Deed)', 'Waqf & Trust Drafting', 'Mortgage Deed'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'हिबानामा', 'वक्फ एवं ट्रस्ट विलेख', 'बंधक पत्र'],
    languages: ['Hindi', 'Urdu', 'Magahi', 'English'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    about: 'Licensed Deed Writer in Gaya district with in-depth knowledge of urban Gaya, Bodhgaya circle rates, and agricultural land transfers.',
    aboutHi: 'गया जिले में लाइसेंस प्राप्त कातिब। गया शहर, बोधगया और ग्रामीण अंचलों की भूमि रजिस्ट्री के दक्ष लेखक।',
    phone: '+91 94314 55102',
    whatsapp: '+91 94314 55102',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '12:30 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 1670,
    reviews: [
      {
        id: 'r8',
        userName: 'Md. Rizwan',
        userLocation: 'Bodhgaya',
        rating: 5,
        date: '01 Aug 2026',
        comment: 'Very polite and highly knowledgeable regarding gift deed exemptions in Bihar.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p8',
    name: 'Advocate Sunil Kumar Thakur',
    nameHi: 'अधिवक्ता सुनील कुमार ठाकुर',
    category: 'Lawyer',
    categoryHi: 'जमीन एवं राजस्व अधिवक्ता',
    rating: 4.9,
    reviewCount: 82,
    experience: 18,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur District & Sessions Court',
    officeHi: 'मुजफ्फरपुर व्यवहार न्यायालय',
    officeType: 'Civil Court',
    chamberAddress: 'Lawyers Chamber Complex, Court Compound, Muzaffarpur',
    verified: true,
    licenseNumber: 'BR/MZP/2008/1190',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 3000,
    tokenFee: 100,
    services: ['Land Dispute Injunction', 'DCLR Title Appeal', 'Batwara (Partition) Suit', 'Fraudulent Registry Cancellation'],
    servicesHi: ['जमीन स्थगन आदेश (Injunction)', 'डीसीएलआर अपील', 'बंटवारा मुकदमा', 'फर्जी केवाला निरस्तीकरण वाद'],
    languages: ['Hindi', 'Bhojpuri', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    about: 'Senior Advocate handling high-stakes land dispute cases, fraudulent deed cancellations, and boundary disputes in Muzaffarpur and Tirhut division.',
    aboutHi: 'मुजफ्फरपुर और तिरहुत प्रमंडल में जमीन विवाद, फर्जी रजिस्ट्री निरस्तीकरण और राजस्व अपीलों के अनुभवी अधिवक्ता।',
    phone: '+91 98354 77610',
    whatsapp: '+91 98354 77610',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['11:00 AM', '01:00 PM', '03:00 PM', '05:00 PM'],
    totalCasesCompleted: 1150,
    reviews: [
      {
        id: 'r9',
        userName: 'Rameshwar Roy',
        userLocation: 'Saraiya, Muzaffarpur',
        rating: 5,
        date: '29 Jul 2026',
        comment: 'Won our land mutation stay in DCLR court within 2 hearings. Great legal depth.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p9',
    name: 'Amin Ganeshwar Sharma',
    nameHi: 'अमीन गणेश्वर शर्मा',
    category: 'Amin / Land Surveyor',
    categoryHi: 'वरिष्ठ अमीन (राजस्व पैमाइश)',
    rating: 4.8,
    reviewCount: 94,
    experience: 24,
    district: 'Bhagalpur',
    districtHi: 'भागलपुर',
    block: 'Kahalgaon',
    office: 'Kahalgaon Sub-Registry',
    officeHi: 'कहलगांव अवर-निबंधन व अंचल कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Near Kahalgaon Anchal Adhikari Office, Bhagalpur',
    verified: true,
    licenseNumber: 'BHR/AMIN/BGP/4102',
    licenseAuthority: 'Revenue Dept, Bhagalpur',
    fee: 2000,
    tokenFee: 100,
    services: ['Land Measurement in Dhur/Katha', 'Boundary Pillar Fixing', 'Cadastral & Revisional Naksha Match', 'Agricultural Field Division'],
    servicesHi: ['धूर/कट्ठा/डिसमिल पैमाइश', 'हदबंदी पिलर स्थापन', 'कैडस्ट्रल व रिविजनल नक्शा मिलान', 'कृषि भूमि बंटवारा नापी'],
    languages: ['Hindi', 'Angika'],
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    about: '24 years of experience as Anchal Amin in Kahalgaon and Pirpainti. Unmatched precision in resolving historic village boundary conflicts.',
    aboutHi: 'कहलगांव और पीरपैंती में 24 वर्षों का अमीन कार्य। पुराने से पुराने नक्शे और जरीब पैमाइश में शत-प्रतिशत सटीकता।',
    phone: '+91 94300 22918',
    whatsapp: '+91 94300 22918',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    timeSlots: ['07:00 AM', '09:00 AM', '11:00 AM', '02:30 PM'],
    totalCasesCompleted: 3400,
    reviews: [
      {
        id: 'r10',
        userName: 'Tribhuvan Singh',
        userLocation: 'Kahalgaon',
        rating: 5,
        date: '25 Jul 2026',
        comment: 'Ganeshwar Amin measured our 4 bigha mango orchard with utmost honesty and village consensus.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p10',
    name: 'Advocate Shailesh Kumar Ray',
    nameHi: 'अधिवक्ता शैलेश कुमार राय',
    category: 'Lawyer',
    categoryHi: 'संपत्ति एवं रेवेन्यू लॉयर',
    rating: 4.9,
    reviewCount: 52,
    experience: 12,
    district: 'Begusarai',
    districtHi: 'बेगूसराय',
    block: 'Begusarai',
    office: 'Begusarai District & Sessions Court',
    officeHi: 'बेगूसराय व्यवहार न्यायालय',
    officeType: 'Civil Court',
    chamberAddress: 'Civil Court Compound, Court Road, Begusarai',
    verified: true,
    licenseNumber: 'BR/BEG/2014/302',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 2800,
    tokenFee: 100,
    services: ['Land Title Verification', 'Dakhil Kharij Objection Filing', 'Deed Cancellation Suit', 'Legal Notice Issuance'],
    servicesHi: ['जमीन स्वामित्व जांच', 'दाखिल खारिज आपत्ति दाखिला', 'रजिस्ट्री निरस्तीकरण वाद', 'कानूनी नोटिस'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    about: 'Dedicated property lawyer in Begusarai and Barauni region. Helps NRIs and out-of-state buyers with verified legal due diligence.',
    aboutHi: 'बेगूसराय एवं बरौनी अंचल में संपत्ति विशेषज्ञ वकील। प्रवासी बिहारियों व गैर-स्थानीय खरीदारों को सुरक्षित जांच सेवा।',
    phone: '+91 97082 66311',
    whatsapp: '+91 97082 66311',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:00 PM', '04:30 PM'],
    totalCasesCompleted: 740,
    reviews: [
      {
        id: 'r11',
        userName: 'Naveen Poddar',
        userLocation: 'Barauni, Begusarai',
        rating: 5,
        date: '11 Aug 2026',
        comment: 'Very professional legal advice on our commercial plot registry.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p11',
    name: 'Sanjeev Kumar Sinha',
    nameHi: 'संजीव कुमार सिन्हा',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.9,
    reviewCount: 105,
    experience: 18,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Patna Sadar',
    office: 'Patna Sadar Registry Office',
    officeHi: 'पटना सदर रजिस्ट्री कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Shed #3, Sadar Registry Campus, Collectorate Ghat Road, Patna',
    verified: true,
    licenseNumber: 'PAT/DW/2006/89',
    licenseAuthority: 'District Registration Office, Patna',
    fee: 2500,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Flat Registry (Apartment Deed)', 'Gift Deed', 'Commercial Land Registry'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'अपार्टमेंट / फ्लैट रजिस्ट्री', 'हिबानामा', 'व्यावसायिक भूमि विलेख'],
    languages: ['Hindi', 'English', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    about: 'Senior Patna Sadar Katib with extensive expertise in commercial and high-value residential deed preparation across Patna city.',
    aboutHi: 'पटना सदर में 18 वर्षों के अनुभवी कातिब। फ्लैट व जमीन रजिस्ट्री के आधिकारिक कागजात में विशेषज्ञता।',
    phone: '+91 94310 99823',
    whatsapp: '+91 94310 99823',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '12:30 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 3900,
    reviews: [
      {
        id: 'r12',
        userName: 'Rajan Gupta',
        userLocation: 'Boring Road, Patna',
        rating: 5,
        date: '14 Aug 2026',
        comment: 'Handled our 3BHK flat registry at Sadar Registry office seamlessly. Zero delays.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p12',
    name: 'Advocate Priya Ranjan Verma (Notary)',
    nameHi: 'अधिवक्ता प्रिय रंजन वर्मा (नोटरी)',
    category: 'Notary',
    categoryHi: 'नोटरी पब्लिक (पटना)',
    rating: 4.8,
    reviewCount: 61,
    experience: 13,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Patna Sadar',
    office: 'Patna Sadar Registry Office Notary Hub',
    officeHi: 'पटना सदर रजिस्ट्री कार्यालय नोटरी केंद्र',
    officeType: 'Registry Office',
    chamberAddress: 'Chamber 18, Collectorate Campus Notary Block, Patna',
    verified: true,
    licenseNumber: 'GOI/NOT/PAT/8190',
    licenseAuthority: 'Ministry of Law & Justice, Govt of India',
    fee: 700,
    tokenFee: 100,
    services: ['Land Agreement Notarization', 'Stamp Paper Affidavit', 'POA Attestation', 'Legal Undertaking'],
    servicesHi: ['जमीन एग्रीमेंट नोटरी', 'शपथ पत्र', 'मुख्तारनामा सत्यापन', 'कानूनी घोषणा पत्र'],
    languages: ['Hindi', 'English'],
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    about: 'Authorized Central Notary Public in Patna. Provides rapid attestation and digital record keeping for real estate and banking agreements.',
    aboutHi: 'पटना में अधिकृत नोटरी पब्लिक। जमीन खरीद-बिक्री एग्रीमेंट व हलफनामे का त्वरित प्रमाणीकरण।',
    phone: '+91 93341 08821',
    whatsapp: '+91 93341 08821',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '01:30 PM', '03:30 PM', '05:00 PM'],
    totalCasesCompleted: 2400,
    reviews: [
      {
        id: 'r13',
        userName: 'Suman Tiwari',
        userLocation: 'Kankarbagh, Patna',
        rating: 5,
        date: '10 Aug 2026',
        comment: 'Very polite and swift notary attestation.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p13',
    name: 'Sanjay Kumar Thakur',
    nameHi: 'संजय कुमार ठाकुर (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 78,
    experience: 14,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Kanti',
    office: 'Kanti Sub-Registry',
    officeHi: 'कांटी उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Shed 4, Kanti Sub-Registry Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'MUZ/KNT/DW/2010/44',
    licenseAuthority: 'Registration Department, Bihar',
    fee: 1800,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed (Hibanama)', 'Partition Deed (Batwara)', 'Agreement to Sale'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'दान पत्र (हिबानामा)', 'बंटवारानामा', 'इकरारनामा'],
    languages: ['Hindi', 'Maithili', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    about: 'Experienced Katib at Kanti Sub-Registry with 14+ years handling agricultural and residential deed registrations.',
    aboutHi: 'कांटी उप-निबंधन कार्यालय में 14 वर्षों से कार्यरत सरकारी लाइसेंसधारी दस्तावेज लेखक।',
    phone: '+91 94318 44521',
    whatsapp: '+91 94318 44521',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 3100,
    reviews: [
      {
        id: 'r14',
        userName: 'Pankaj Kumar',
        userLocation: 'Kanti, Muzaffarpur',
        rating: 5,
        date: '12 Aug 2026',
        comment: 'Very smooth registry process at Kanti Sub-Registry. Done in 1 hour.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p14',
    name: 'Manoj Kumar Pandey',
    nameHi: 'मनोज कुमार पाण्डेय (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.9,
    reviewCount: 92,
    experience: 16,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Motipur',
    office: 'Motipur Sub-Registry',
    officeHi: 'मोतीपुर उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Chamber 2, Motipur Registry Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'MUZ/MTP/DW/2008/19',
    licenseAuthority: 'Registration Department, Bihar',
    fee: 2000,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed', 'Family Settlement', 'Mortgage Deed'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'हिबानामा', 'पारिवारिक बंटवारा', 'रेहननामा'],
    languages: ['Hindi', 'Maithili'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    about: 'Dedicated Deed Writer at Motipur Sub-Registry offering precise land deed drafting and verification.',
    aboutHi: 'मोतीपुर उप-निबंधन कार्यालय में 16 वर्षों से निष्पक्ष व कानूनी रूप से शुद्ध दस्तावेज लेखक।',
    phone: '+91 94314 77219',
    whatsapp: '+91 94314 77219',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '01:00 PM', '03:30 PM'],
    totalCasesCompleted: 3450,
    reviews: []
  },
  {
    id: 'p15',
    name: 'Rakesh Sharma',
    nameHi: 'राकेश शर्मा (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.7,
    reviewCount: 54,
    experience: 11,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Paroo',
    office: 'Paroo Sub-Registry',
    officeHi: 'पारू उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Shed 1, Paroo Sub-Registry Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'MUZ/PRU/DW/2013/61',
    licenseAuthority: 'Registration Department, Bihar',
    fee: 1700,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Will Deed (Wasiyatnama)', 'Batwara'],
    servicesHi: ['केवाला', 'वसीयतनामा', 'पारिवारिक बंटवारा'],
    languages: ['Hindi', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    about: 'Paroo Sub-Registry certified Katib specialized in agricultural land deeds.',
    aboutHi: 'पारू उप-निबंधन कार्यालय के अनुभवी कातिब।',
    phone: '+91 94316 11209',
    whatsapp: '+91 94316 11209',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['10:00 AM', '12:30 PM', '03:00 PM'],
    totalCasesCompleted: 2200,
    reviews: []
  },
  {
    id: 'p16',
    name: 'Alok Kumar',
    nameHi: 'आलोक कुमार (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 63,
    experience: 12,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Sakra',
    office: 'Sakra Sub-Registry',
    officeHi: 'सकरा उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Desk 5, Sakra Sub-Registry Complex, Muzaffarpur',
    verified: true,
    licenseNumber: 'MUZ/SKR/DW/2012/38',
    licenseAuthority: 'Registration Department, Bihar',
    fee: 1800,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed', 'Mutation Assistance'],
    servicesHi: ['केवाला', 'दान पत्र', 'दाखिल खारिज सहायता'],
    languages: ['Hindi'],
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    about: 'Sakra Sub-Registry specialist in clean deed drafting.',
    aboutHi: 'सकरा निबंधन कार्यालय के विश्वसनीय दस्तावेज लेखक।',
    phone: '+91 94319 88310',
    whatsapp: '+91 94319 88310',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '01:30 PM', '04:00 PM'],
    totalCasesCompleted: 2600,
    reviews: []
  },
  {
    id: 'p17',
    name: 'Amin Devendra Prasad',
    nameHi: 'अमीन देवेन्द्र प्रसाद',
    category: 'Amin / Land Surveyor',
    categoryHi: 'प्रशिक्षित सरकारी अमीन',
    rating: 4.9,
    reviewCount: 112,
    experience: 20,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur Registry Office',
    officeHi: 'मुजफ्फरपुर रजिस्ट्री कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Musahari Anchal & Collectorate Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'SURV/BHR/MUZ/MSH/2004',
    licenseAuthority: 'Directorate of Land Records & Survey, Bihar',
    fee: 2200,
    tokenFee: 100,
    services: ['Katha/Dhur Measurement', 'Boundary Demarcation (Hadbandi)', 'Cadastral Map Matching', 'Pillar Fixing'],
    servicesHi: ['कट्ठा/धूर नापी', 'हदबंदी पिलर स्थापन', 'कैडस्ट्रल नक्शा मिलान', 'विवाद समाधान'],
    languages: ['Hindi', 'Maithili'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    about: 'Senior revenue Amin for Musahari Block and Muzaffarpur Sadar. Certified ETS survey master.',
    aboutHi: 'मुसहरी अंचल व मुजफ्फरपुर सदर के 20 वर्षीय अनुभवी सरकारी प्रशिक्षित अमीन।',
    phone: '+91 98352 11984',
    whatsapp: '+91 98352 11984',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    timeSlots: ['07:30 AM', '10:30 AM', '02:30 PM'],
    totalCasesCompleted: 4200,
    reviews: [
      {
        id: 'r15',
        userName: 'Shyam Sundar',
        userLocation: 'Musahari, Muzaffarpur',
        rating: 5,
        date: '08 Aug 2026',
        comment: 'Accurate survey with digital ETS machine in Musahari block.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p18',
    name: 'Amin Satyendra Singh',
    nameHi: 'अमीन सत्येन्द्र सिंह',
    category: 'Amin / Land Surveyor',
    categoryHi: 'सरकारी सर्वेयर (मोतीपुर)',
    rating: 4.8,
    reviewCount: 75,
    experience: 15,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Motipur',
    office: 'Motipur Sub-Registry',
    officeHi: 'मोतीपुर उप-निबंधन कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Motipur Block Revenue Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'SURV/BHR/MUZ/MTP/2009',
    licenseAuthority: 'Directorate of Land Records & Survey, Bihar',
    fee: 2000,
    tokenFee: 100,
    services: ['Plot Demarcation', 'CS/RS Khatian Survey', 'Field Measurement'],
    servicesHi: ['जमीन सीमांकन', 'खतियान सर्वे', 'जरीब पैमाइश'],
    languages: ['Hindi'],
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    about: 'Certified revenue Amin serving Motipur revenue block.',
    aboutHi: 'मोतीपुर अंचल के प्रमाणित अमीन।',
    phone: '+91 98354 66120',
    whatsapp: '+91 98354 66120',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['08:00 AM', '11:00 AM', '03:00 PM'],
    totalCasesCompleted: 2900,
    reviews: []
  },
  {
    id: 'p19',
    name: 'Amin Upendra Jha',
    nameHi: 'अमीन उपेन्द्र झा',
    category: 'Amin / Land Surveyor',
    categoryHi: 'प्रशिक्षित अमीन (औराई)',
    rating: 4.7,
    reviewCount: 48,
    experience: 13,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Aurai',
    office: 'Muzaffarpur Registry Office',
    officeHi: 'मुजफ्फरपुर रजिस्ट्री कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Aurai Circle Office Campus, Muzaffarpur',
    verified: true,
    licenseNumber: 'SURV/BHR/MUZ/AUR/2011',
    licenseAuthority: 'Directorate of Land Records & Survey, Bihar',
    fee: 1800,
    tokenFee: 100,
    services: ['Land Measurement', 'Boundary Hadbandi', 'Decimal to Katha conversion'],
    servicesHi: ['जमीन नापी', 'हदबंदी', 'डिसमिल से कट्ठा रूपांतरण'],
    languages: ['Hindi', 'Maithili'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    about: 'Aurai block specialist with deep knowledge of local survey sheets.',
    aboutHi: 'औराई अंचल के भूमि नक्शा विशेषज्ञ।',
    phone: '+91 98357 88102',
    whatsapp: '+91 98357 88102',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['08:00 AM', '11:30 AM', '03:30 PM'],
    totalCasesCompleted: 2100,
    reviews: []
  },
  {
    id: 'p20',
    name: 'Ashok Kumar Verma',
    nameHi: 'अशोक कुमार वर्मा (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (दानापुर)',
    rating: 4.9,
    reviewCount: 88,
    experience: 17,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Danapur',
    office: 'Danapur Sub-Registry',
    officeHi: 'दानापुर उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Shed 7, Danapur Sub-Registry Campus, Patna',
    verified: true,
    licenseNumber: 'PAT/DNP/DW/2007/21',
    licenseAuthority: 'District Registration Office, Patna',
    fee: 2200,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Flat Registry', 'Gift Deed', 'POA'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'फ्लैट रजिस्ट्री', 'दान पत्र', 'मुख्तारनामा'],
    languages: ['Hindi', 'English', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    about: 'Danapur Sub-Registry leading deed writer for apartments, residential plots, and agricultural land.',
    aboutHi: 'दानापुर उप-निबंधन कार्यालय में 17 वर्षों के प्रतिष्ठित दस्तावेज लेखक।',
    phone: '+91 94310 55180',
    whatsapp: '+91 94310 55180',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 3800,
    reviews: []
  },
  {
    id: 'p21',
    name: 'Tribhuvan Nath',
    nameHi: 'त्रिभुवन नाथ (कातिब)',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (बिक्रम)',
    rating: 4.8,
    reviewCount: 52,
    experience: 15,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Bikram',
    office: 'Bikram Sub-Registry',
    officeHi: 'बिक्रम उप-निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Bikram Registry Office Campus, Patna',
    verified: true,
    licenseNumber: 'PAT/BKR/DW/2009/11',
    licenseAuthority: 'District Registration Office, Patna',
    fee: 2000,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed', 'Batwara'],
    servicesHi: ['केवाला', 'हिबानामा', 'बंटवारानामा'],
    languages: ['Hindi', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    about: 'Bikram Sub-Registry deed drafting expert.',
    aboutHi: 'बिक्रम उप-निबंधन कार्यालय के अनुभवी कातिब।',
    phone: '+91 94312 33419',
    whatsapp: '+91 94312 33419',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['10:30 AM', '01:00 PM', '03:30 PM'],
    totalCasesCompleted: 2700,
    reviews: []
  },
  {
    id: 'p22',
    name: 'Amin Shambhu Sharan',
    nameHi: 'अमीन शंभू शरण',
    category: 'Amin / Land Surveyor',
    categoryHi: 'प्रशिक्षित सरकारी अमीन (बिहटा)',
    rating: 4.9,
    reviewCount: 96,
    experience: 19,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Bihta',
    office: 'Danapur Sub-Registry',
    officeHi: 'दानापुर उप-निबंधन कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Bihta Circle Office & Block Campus, Patna',
    verified: true,
    licenseNumber: 'SURV/BHR/PAT/BHT/2005',
    licenseAuthority: 'Directorate of Land Records & Survey, Bihar',
    fee: 2500,
    tokenFee: 100,
    services: ['Bihta Industrial & Residential Survey', 'Hadbandi', 'GPS Coordinates'],
    servicesHi: ['बिहटा जमीन नापी', 'हदबंदी', 'जीपीएस सीमांकन'],
    languages: ['Hindi', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    about: 'Bihta Block top Amin specializing in industrial corridors, township plots, and agricultural land measurement.',
    aboutHi: 'बिहटा अंचल व इंडस्ट्रियल एरिया के जाने-माने वरिष्ठ सरकारी अमीन।',
    phone: '+91 98350 44210',
    whatsapp: '+91 98350 44210',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    timeSlots: ['07:30 AM', '11:00 AM', '03:00 PM'],
    totalCasesCompleted: 4600,
    reviews: []
  }
];

export const initialBookings: Booking[] = [
  {
    id: 'b-101',
    bookingNumber: 'LC-BHR-2026-8842',
    professionalId: 'p1',
    professionalName: 'Rajesh Kumar Singh',
    professionalCategory: 'Deed Writer (Katib)',
    professionalPhone: '+91 94312 88410',
    professionalOffice: 'Bhagalpur Sadar Registry Office',
    clientName: 'Vivek Ranjan',
    clientPhone: '+91 98765 43210',
    clientEmail: 'vivek.ranjan@example.com',
    district: 'Bhagalpur',
    serviceSelected: 'Sale Deed (Kewala / रजिस्ट्री)',
    appointmentDate: '2026-08-20',
    appointmentTime: '11:30 AM',
    plotDetails: {
      khataNumber: '44',
      khesraNumber: '112/A',
      mauza: 'Sabour',
      thanaNumber: '184',
      areaSize: '3.5 Katha'
    },
    professionalFee: 2000,
    tokenPaid: 100,
    remainingAtOffice: 1900,
    status: 'Confirmed',
    paymentMethod: 'UPI',
    transactionId: 'UPI/2026/8931124401',
    createdAt: '2026-08-16T14:30:00Z',
    notes: 'Drafting sale deed for ancestral agricultural plot transfer.'
  }
];
