import { Professional } from '../types';

export const mockProfessionals: Professional[] = [
  {
    id: 'p1',
    name: 'Rajesh Kumar Singh',
    nameHi: 'राजेश कुमार सिंह',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.9,
    reviewCount: 148,
    experience: 16,
    district: 'Bhagalpur',
    districtHi: 'भागलपुर',
    block: 'Jagdishpur',
    office: 'Bhagalpur Sadar Registry Office',
    officeHi: 'भागलपुर सदर रजिस्ट्री ऑफिस',
    officeType: 'Registry Office',
    chamberAddress: 'Shed No. 14, Near Sub-Registrar Gate, Registry Office Campus, Bhagalpur',
    verified: true,
    licenseNumber: 'BGP/DW/2009/482',
    licenseAuthority: 'District Registration Department, Bihar',
    fee: 2000,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Gift Deed (Hibanama)', 'Partition Deed (Batwarinama)', 'Agreement to Sale'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'दान पत्र (हिबानामा)', 'बंटवारानामा', 'बिक्री इकरारनामा'],
    languages: ['Hindi', 'Angika', 'English'],
    image: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=300&auto=format&fit=crop&q=80',
    about: 'Senior Licensed Deed Writer (Katib) with 16+ years of expertise in Bhagalpur district. Expert in drafting error-free Kewala deeds, boundary verification (Chauhaddi), and immediate registry token clearance.',
    aboutHi: 'भागलपुर जिले में 16+ वर्षों के अनुभव के साथ वरिष्ठ लाइसेंस प्राप्त कातिब। त्रुटिरहित केवाला लेखन, चौहद्दी मिलान और त्वरित निबंधन में विशेषज्ञता।',
    phone: '+91 94312 88410',
    whatsapp: '+91 94312 88410',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM', '05:00 PM'],
    totalCasesCompleted: 1420,
    reviews: [
      {
        id: 'r1',
        userName: 'Manoj Choudhary',
        userLocation: 'Sabour, Bhagalpur',
        rating: 5,
        date: '12 Aug 2026',
        comment: 'Rajesh ji drafted our commercial land kewala in just 3 hours. Handled the circle rate calculation and token without any hassle. Highly recommended!',
        verifiedBooking: true
      },
      {
        id: 'r2',
        userName: 'Sunita Devi',
        userLocation: 'Nathnagar',
        rating: 5,
        date: '28 Jul 2026',
        comment: 'Very honest Katib. Transparent regarding official stamp duty. No hidden charges.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p2',
    name: 'Advocate Anand Vardhan',
    nameHi: 'अधिवक्ता आनंद वर्धन',
    category: 'Lawyer',
    categoryHi: 'जमीन एवं संपत्ति वकील',
    rating: 4.9,
    reviewCount: 96,
    experience: 14,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Patna Sadar',
    office: 'Patna Sadar Registry Office',
    officeHi: 'पटना सदर रजिस्ट्री ऑफिस एवं सिविल कोर्ट',
    officeType: 'Civil Court',
    chamberAddress: 'Chamber #204, High Court Advocates Association / Danapur Registry Road, Patna',
    verified: true,
    licenseNumber: 'BR/PAT/2012/8821',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 3500,
    tokenFee: 100,
    services: ['30-Year Title Search', 'Dakhil Kharij Dispute', 'DCLR / BLT Appeals', 'Land Partition Suit', 'Legal Opinion Certificate'],
    servicesHi: ['30 वर्षीय टाइटल जांच', 'दाखिल-खारिज विवाद', 'डीसीएलआर अपील', 'जमीन बंटवारा वाद', 'कानूनी राय प्रमाण पत्र'],
    languages: ['Hindi', 'Bhojpuri', 'English', 'Magahi'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    about: 'Practicing Land & Property Lawyer representing clients in Patna High Court, Civil Courts, and District Revenue Forums. Specializes in ancestral title checks and complex Dakhil Kharij rejections.',
    aboutHi: 'पटना हाईकोर्ट और राजस्व न्यायालयों में सक्रिय संपत्ति अधिवक्ता। पुश्तैनी जमीन के स्वामित्व प्रमाणन व विवादित दाखिल-खारिज मामलों में विशेषज्ञ।',
    phone: '+91 98350 44129',
    whatsapp: '+91 98350 44129',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '12:00 PM', '02:30 PM', '04:30 PM', '06:00 PM'],
    totalCasesCompleted: 890,
    reviews: [
      {
        id: 'r3',
        userName: 'Alok Ranjan',
        userLocation: 'Kankarbagh, Patna',
        rating: 5,
        date: '05 Aug 2026',
        comment: 'Advocate Anand did a complete 30-year search report on our plot in Bihta. Saved us from a disputed property with multiple fake claimants.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p3',
    name: 'Amin Ramashish Yadav',
    nameHi: 'अमीन रामाशीष यादव',
    category: 'Amin / Land Surveyor',
    categoryHi: 'सरकारी प्रशिक्षित अमीन (भूमि सर्वेयर)',
    rating: 4.8,
    reviewCount: 112,
    experience: 19,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Danapur',
    office: 'Danapur Sub-Registry',
    officeHi: 'दानापुर अवर-निबंधन व अंचल कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Near Danapur Block Circle Office, Khagaul Road, Danapur',
    verified: true,
    licenseNumber: 'BHR/AMIN/PAT/9871',
    licenseAuthority: 'Revenue & Land Reforms Dept, Bihar',
    fee: 2200,
    tokenFee: 100,
    services: ['Land Measurement (Katha/Dhur)', 'ETS Electronic Survey', 'Boundary Demarcation (Hadbandi)', 'Revisional Map Naksha Matching'],
    servicesHi: ['कट्ठा/धूर/डिसमिल जमीन नापी', 'ईटीएस इलेक्ट्रॉनिक पैमाइश', 'हदबंदी एवं सीमा पिलर', 'राजस्व नक्शा मिलान'],
    languages: ['Hindi', 'Bhojpuri', 'Magahi'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    about: 'Govt Certified Senior Amin with Gunter Chain, Total Station & GPS mapping expertise. Has surveyed over 4,000 plots in Patna, Danapur, Bihta, and Naubatpur blocks without boundary inaccuracies.',
    aboutHi: 'सरकारी प्रमाणित वरिष्ठ अमीन। जरीब (चेन), टोटल स्टेशन एवं जीपीएस द्वारा सटीक पैमाइश। दानापुर, बिहटा और पटना अंचल में 4000+ खेतों और प्लॉटों का सफल सीमांकन।',
    phone: '+91 94702 11984',
    whatsapp: '+91 94702 11984',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Sunday'],
    timeSlots: ['07:30 AM', '09:00 AM', '11:00 AM', '03:00 PM'],
    totalCasesCompleted: 2150,
    reviews: [
      {
        id: 'r4',
        userName: 'Surendra Prasad',
        userLocation: 'Naubatpur, Patna',
        rating: 5,
        date: '02 Aug 2026',
        comment: 'Ramashish ji resolved a 5-year old boundary confusion with the neighbor in 2 hours using village cadastral map.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p4',
    name: 'Santosh Kumar Mishra (Notary)',
    nameHi: 'संतोष कुमार मिश्रा (नोटरी)',
    category: 'Notary',
    categoryHi: 'नोटरी पब्लिक (भारत सरकार)',
    rating: 4.9,
    reviewCount: 73,
    experience: 11,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur Registry Office',
    officeHi: 'मुजफ्फरपुर निबंधन कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Collectorate Campus, Opposite Sub-Registry Building, Muzaffarpur',
    verified: true,
    licenseNumber: 'GOI/NOT/MZP/4419',
    licenseAuthority: 'Ministry of Law & Justice, Govt of India',
    fee: 800,
    tokenFee: 100,
    services: ['Agreement Attestation', 'Land Affidavit / Shapath Patra', 'General Power of Attorney (GPA)', 'Will Notarization'],
    servicesHi: ['एग्रीमेंट सत्यापन', 'जमीन शपथ पत्र', 'मुख्तारनामा (GPA)', 'वसीयतनामा प्रमाणीकरण'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    about: 'Government Appointed Notary Public for Muzaffarpur district. Instant stamping, online register entry, and tamper-proof security holographic attestations.',
    aboutHi: 'मुजफ्फरपुर जिले के लिए भारत सरकार द्वारा नियुक्त नोटरी पब्लिक। तुरंत शपथ पत्र प्रमाणीकरण व सुरक्षित होलोग्राम सत्यापन।',
    phone: '+91 93081 77209',
    whatsapp: '+91 93081 77209',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '01:30 PM', '03:30 PM', '05:00 PM'],
    totalCasesCompleted: 3100,
    reviews: [
      {
        id: 'r5',
        userName: 'Vikash Jha',
        userLocation: 'Kanti, Muzaffarpur',
        rating: 5,
        date: '10 Aug 2026',
        comment: 'Quick and hassle-free affidavit for our land mutation submission at Circle Office.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p5',
    name: 'Birendra Kumar Jha',
    nameHi: 'बीरेन्द्र कुमार झा',
    category: 'Deed Writer',
    categoryHi: 'वरिष्ठ दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 88,
    experience: 22,
    district: 'Darbhanga',
    districtHi: 'दरभंगा',
    block: 'Darbhanga Sadar',
    office: 'Darbhanga Sadar Registry Office',
    officeHi: 'दरभंगा सदर रजिस्ट्री कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Block 2, Near Treasury Building, Sadar Registry, Darbhanga',
    verified: true,
    licenseNumber: 'DBG/KATIB/1998/104',
    licenseAuthority: 'District Registration Office, Darbhanga',
    fee: 1800,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Exchange Deed (Badlainama)', 'Gift Deed', 'Lease Registration'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'बदलैननामा (जमीन अदला-बदली)', 'हिबानामा', 'लीज पट्टा रजिस्ट्री'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    about: '22+ years seasoned Katib in Darbhanga and Madhubani region. Masters in complex joint family partitions (Batwarinama) and municipal MVR land valuation.',
    aboutHi: 'दरभंगा और मिथिलांचल में 22+ वर्षों का प्रतिष्ठित कातिब। जटिल पारिवारिक बंटवारा और सरकारी एमवीआर मूल्यांकन में माहिर।',
    phone: '+91 94318 66201',
    whatsapp: '+91 94318 66201',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 2840,
    reviews: [
      {
        id: 'r6',
        userName: 'Abhishek Mishra',
        userLocation: 'Benipur, Darbhanga',
        rating: 5,
        date: '04 Aug 2026',
        comment: 'Very thorough with Khatiyan entries and legal clauses. No clerical error on the final stamp.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p6',
    name: 'Pooja Srivastava (Revenue Consultant)',
    nameHi: 'पूजा श्रीवास्तव (राजस्व सलाहकार)',
    category: 'Document Checker',
    categoryHi: 'जमीन दस्तावेज व दाखिल खारिज परीक्षक',
    rating: 4.9,
    reviewCount: 64,
    experience: 9,
    district: 'Patna',
    districtHi: 'पटना',
    block: 'Patna Sadar',
    office: 'Patna Sadar Registry Office',
    officeHi: 'पटना सदर रजिस्ट्री व अंचल कार्यालय',
    officeType: 'Independent Chamber',
    chamberAddress: 'Office #12, Revenue Hub, Exhibition Road, Patna',
    verified: true,
    licenseNumber: 'BHR/REV/PAT/2017/51',
    licenseAuthority: 'Bihar Revenue Records Verification Board',
    fee: 1200,
    tokenFee: 100,
    services: ['Bihar Bhumi Jamabandi Check', 'Khatian CS/RS Verification', 'Dakhil Kharij Status Audit', 'LPC Application Preparation'],
    servicesHi: ['बिहार भूमि जमाबंदी ऑनलाइन जांच', 'खतियान सीएस/आरएस मिलान', 'दाखिल खारिज स्टेटस ऑडिट', 'एलपीसी भू-स्वामित्व आवेदन'],
    languages: ['Hindi', 'English', 'Bhojpuri'],
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    about: 'Specialist in Bihar Bhumi portals (biharbhumi.bihar.gov.in), digital Jamabandi corrections, and verifying encumbrance-free records prior to registry purchase.',
    aboutHi: 'बिहार भूमि पोर्टल, डिजिटल जमाबंदी सुधार और जमीन खरीदने से पहले पूरे सरकारी रिकॉर्ड की निष्पक्ष जांच में विशेषज्ञ।',
    phone: '+91 97714 33290',
    whatsapp: '+91 97714 33290',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '04:00 PM', '06:00 PM'],
    totalCasesCompleted: 1100,
    reviews: [
      {
        id: 'r7',
        userName: 'Deepak Kumar',
        userLocation: 'Gola Road, Danapur',
        rating: 5,
        date: '08 Aug 2026',
        comment: 'Pooja ji checked the Jamabandi and pointed out that the seller was not the single owner. Prevented huge financial loss!',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p7',
    name: 'Mohammad Tariq Anwar',
    nameHi: 'मोहम्मद तारिक अनवर',
    category: 'Deed Writer',
    categoryHi: 'दस्तावेज लेखक (कातिब)',
    rating: 4.8,
    reviewCount: 76,
    experience: 15,
    district: 'Gaya',
    districtHi: 'गया',
    block: 'Gaya Town',
    office: 'Gaya Sadar Registry Office',
    officeHi: 'गया सदर रजिस्ट्री कार्यालय',
    officeType: 'Registry Office',
    chamberAddress: 'Near Gaya Collectorate, Registry Campus, Gaya',
    verified: true,
    licenseNumber: 'GAY/DW/2011/391',
    licenseAuthority: 'Registration Department, Gaya',
    fee: 1900,
    tokenFee: 100,
    services: ['Sale Deed (Kewala)', 'Hibanama (Gift Deed)', 'Waqf & Trust Drafting', 'Mortgage Deed'],
    servicesHi: ['केवाला (बिक्री पत्र)', 'हिबानामा', 'वक्फ एवं ट्रस्ट विलेख', 'बंधक पत्र'],
    languages: ['Hindi', 'Urdu', 'Magahi', 'English'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    about: 'Licensed Deed Writer in Gaya district with in-depth knowledge of urban Gaya, Bodhgaya circle rates, and agricultural land transfers.',
    aboutHi: 'गया जिले में लाइसेंस प्राप्त कातिब। गया शहर, बोधगया और ग्रामीण अंचलों की भूमि रजिस्ट्री के दक्ष लेखक।',
    phone: '+91 94314 55102',
    whatsapp: '+91 94314 55102',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:30 AM', '12:30 PM', '02:30 PM', '04:30 PM'],
    totalCasesCompleted: 1670,
    reviews: [
      {
        id: 'r8',
        userName: 'Md. Rizwan',
        userLocation: 'Bodhgaya',
        rating: 5,
        date: '01 Aug 2026',
        comment: 'Very polite and highly knowledgeable regarding gift deed exemptions in Bihar.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p8',
    name: 'Advocate Sunil Kumar Thakur',
    nameHi: 'अधिवक्ता सुनील कुमार ठाकुर',
    category: 'Lawyer',
    categoryHi: 'जमीन एवं राजस्व अधिवक्ता',
    rating: 4.9,
    reviewCount: 82,
    experience: 18,
    district: 'Muzaffarpur',
    districtHi: 'मुजफ्फरपुर',
    block: 'Musahari',
    office: 'Muzaffarpur Registry Office',
    officeHi: 'मुजफ्फरपुर सिविल कोर्ट व रजिस्ट्री',
    officeType: 'Civil Court',
    chamberAddress: 'Lawyers Chamber Complex, Court Compound, Muzaffarpur',
    verified: true,
    licenseNumber: 'BR/MZP/2008/1190',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 3000,
    tokenFee: 100,
    services: ['Land Dispute Injunction', 'DCLR Title Appeal', 'Batwara (Partition) Suit', 'Fraudulent Registry Cancellation'],
    servicesHi: ['जमीन स्थगन आदेश (Injunction)', 'डीसीएलआर अपील', 'बंटवारा मुकदमा', 'फर्जी केवाला निरस्तीकरण वाद'],
    languages: ['Hindi', 'Bhojpuri', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    about: 'Senior Advocate handling high-stakes land dispute cases, fraudulent deed cancellations, and boundary disputes in Muzaffarpur and Tirhut division.',
    aboutHi: 'मुजफ्फरपुर और तिरहुत प्रमंडल में जमीन विवाद, फर्जी रजिस्ट्री निरस्तीकरण और राजस्व अपीलों के अनुभवी अधिवक्ता।',
    phone: '+91 98354 77610',
    whatsapp: '+91 98354 77610',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['11:00 AM', '01:00 PM', '03:00 PM', '05:00 PM'],
    totalCasesCompleted: 1150,
    reviews: [
      {
        id: 'r9',
        userName: 'Rameshwar Roy',
        userLocation: 'Saraiya, Muzaffarpur',
        rating: 5,
        date: '29 Jul 2026',
        comment: 'Won our land mutation stay in DCLR court within 2 hearings. Great legal depth.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p9',
    name: 'Amin Ganeshwar Sharma',
    nameHi: 'अमीन गणेश्वर शर्मा',
    category: 'Amin / Land Surveyor',
    categoryHi: 'वरिष्ठ अमीन (राजस्व पैमाइश)',
    rating: 4.8,
    reviewCount: 94,
    experience: 24,
    district: 'Bhagalpur',
    districtHi: 'भागलपुर',
    block: 'Kahalgaon',
    office: 'Kahalgaon Sub-Registry',
    officeHi: 'कहलगांव अवर-निबंधन व अंचल कार्यालय',
    officeType: 'Block Office',
    chamberAddress: 'Near Kahalgaon Anchal Adhikari Office, Bhagalpur',
    verified: true,
    licenseNumber: 'BHR/AMIN/BGP/4102',
    licenseAuthority: 'Revenue Dept, Bhagalpur',
    fee: 2000,
    tokenFee: 100,
    services: ['Land Measurement in Dhur/Katha', 'Boundary Pillar Fixing', 'Cadastral & Revisional Naksha Match', 'Agricultural Field Division'],
    servicesHi: ['धूर/कट्ठा/डिसमिल पैमाइश', 'हदबंदी पिलर स्थापन', 'कैडस्ट्रल व रिविजनल नक्शा मिलान', 'कृषि भूमि बंटवारा नापी'],
    languages: ['Hindi', 'Angika'],
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    about: '24 years of experience as Anchal Amin in Kahalgaon and Pirpainti. Unmatched precision in resolving historic village boundary conflicts.',
    aboutHi: 'कहलगांव और पीरपैंती में 24 वर्षों का अमीन कार्य। पुराने से पुराने नक्शे और जरीब पैमाइश में शत-प्रतिशत सटीकता।',
    phone: '+91 94300 22918',
    whatsapp: '+91 94300 22918',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    timeSlots: ['07:00 AM', '09:00 AM', '11:00 AM', '02:30 PM'],
    totalCasesCompleted: 3400,
    reviews: [
      {
        id: 'r10',
        userName: 'Tribhuvan Singh',
        userLocation: 'Kahalgaon',
        rating: 5,
        date: '25 Jul 2026',
        comment: 'Ganeshwar Amin measured our 4 bigha mango orchard with utmost honesty and village consensus.',
        verifiedBooking: true
      }
    ]
  },
  {
    id: 'p10',
    name: 'Advocate Shailesh Kumar Ray',
    nameHi: 'अधिवक्ता शैलेश कुमार राय',
    category: 'Lawyer',
    categoryHi: 'संपत्ति एवं रेवेन्यू लॉयर',
    rating: 4.9,
    reviewCount: 52,
    experience: 12,
    district: 'Begusarai',
    districtHi: 'बेगूसराय',
    block: 'Begusarai',
    office: 'Begusarai Sadar Registry Office',
    officeHi: 'बेगूसराय सदर रजिस्ट्री व व्यवहार न्यायालय',
    officeType: 'Civil Court',
    chamberAddress: 'Civil Court Compound, Court Road, Begusarai',
    verified: true,
    licenseNumber: 'BR/BEG/2014/302',
    licenseAuthority: 'Bar Council of Bihar',
    fee: 2800,
    tokenFee: 100,
    services: ['Land Title Verification', 'Dakhil Kharij Objection Filing', 'Deed Cancellation Suit', 'Legal Notice Issuance'],
    servicesHi: ['जमीन स्वामित्व जांच', 'दाखिल खारिज आपत्ति दाखिला', 'रजिस्ट्री निरस्तीकरण वाद', 'कानूनी नोटिस'],
    languages: ['Hindi', 'Maithili', 'English'],
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    about: 'Dedicated property lawyer in Begusarai and Barauni region. Helps NRIs and out-of-state buyers with verified legal due diligence.',
    aboutHi: 'बेगूसराय एवं बरौनी अंचल में संपत्ति विशेषज्ञ वकील। प्रवासी बिहारियों व गैर-स्थानीय खरीदारों को सुरक्षित जांच सेवा।',
    phone: '+91 97082 66311',
    whatsapp: '+91 97082 66311',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '12:00 PM', '02:00 PM', '04:30 PM'],
    totalCasesCompleted: 740,
    reviews: [
      {
        id: 'r11',
        userName: 'Naveen Poddar',
        userLocation: 'Barauni, Begusarai',
        rating: 5,
        date: '11 Aug 2026',
        comment: 'Very professional legal advice on our commercial plot registry.',
        verifiedBooking: true
      }
    ]
  }
];

export const initialBookings = [
  {
    id: 'b-101',
    bookingNumber: 'LC-BHR-2026-8842',
    professionalId: 'p1',
    professionalName: 'Rajesh Kumar Singh',
    professionalCategory: 'Deed Writer (Katib)',
    professionalPhone: '+91 94312 88410',
    professionalOffice: 'Bhagalpur Sadar Registry Office',
    clientName: 'Vivek Ranjan',
    clientPhone: '+91 98765 43210',
    clientEmail: 'vivek.ranjan@example.com',
    district: 'Bhagalpur',
    serviceSelected: 'Sale Deed (Kewala / रजिस्ट्री)',
    appointmentDate: '2026-08-20',
    appointmentTime: '11:30 AM',
    plotDetails: {
      khataNumber: '44',
      khesraNumber: '112/A',
      mauza: 'Sabour',
      thanaNumber: '184',
      areaSize: '3.5 Katha'
    },
    professionalFee: 2000,
    tokenPaid: 100,
    remainingAtOffice: 1900,
    status: 'Confirmed' as const,
    paymentMethod: 'UPI' as const,
    transactionId: 'UPI/2026/8931124401',
    createdAt: '2026-08-16T14:30:00Z',
    notes: 'Drafting sale deed for ancestral agricultural plot transfer.'
  }
];
